---
- name: Install and start the service
  hosts: all

  tasks:
  - name: Installing nginx
    yum:
      name: nginx
      state: present
  - name: Starting the nginx service
    service: 
      name: nginx
      state: started
      enabled: true
