---
- name: User Management
  hosts: all

  tasks:
  - name: User Creation
    user:
      name: Shiv_Gupta
      comment: New User adding for Dev Team
      shell: /bin/bash
      groups: dev,QA,devops,admin